### ISSUE TITLE
feat: Connect ui and server

### ISSUE THREAD

**Issue by Sciator** [Sciator/hana#19]
**Feature**
Connect ui with server and serve mock data

**Task**
- [ ] Create documentation and specify routes for api communications
- [X] Create universal fetch function for UI (using common interface)
- [ ] Add advanced router definitions for ui (like `/article/:id/` where `:id` will be replace with `articleId`)
- [ ] Create routers at server
- [ ] Connect mocs at server to serve fetch function (when server started with some flag to use mocks)
