### ISSUE TITLE
feat: Connect db and server

### ISSUE THREAD

**Issue by Sciator** [Sciator/hana#20]
**Feature**

**Task**
- [ ] Create models based on example **typesafe** models
- [ ] Create db views to follow fetch interface style
- [ ] Connect db to routers _(after #21 done)_
- [ ] Create db integration tests using REST api
