### ISSUE TITLE
feat(common): Routes

### ISSUE THREAD

**Issue by Sciator** [Sciator/hana#21]
**feature**
URL routers for api and server.

**tasks**
 - [ ] Create routes definitions that will be used for api inside server+ui.
 - [ ] Follow style of routes used inside api and use it for routing in react router.
 - [ ] Create empty endpoints with routes at server (all endpoints will just throw error but will exist and has type definitions in it)
