### ISSUE TITLE
feat(ui): static pages

### ISSUE THREAD

**Issue by Sciator** [Sciator/hana#6]
**Feature**
Create page as is in prototypes

**Tasks**
 - [x] **Create static html - Martin**
  - [x] Main page
  - [x] Events
  - [x] Add/edit events
  - [x] Trade
  - [x] Add/edit trade
  - [x] JobAds
  - [x] Add/edit JobAds
  - [x] Profile
  - [ ] Statistics
  - [x] Log in/Register?
  - [x] Log out?

 - [x] **Create layout styling - Lucia**
 - [x] **Break into reusable components (break into more files - split layouts/pages/components etc. folders) - Martin**
 - [x] **Create full styling - Lucia**

**Additional context**

Pages prototypes:
* Main page
![hana-main](https://user-images.githubusercontent.com/39964450/96374908-f1c50980-1175-11eb-991f-759bb70ad078.png)
* Event page
![hana-events](https://user-images.githubusercontent.com/39964450/96374911-f689bd80-1175-11eb-9a2c-620f2dfc0711.png)
* Trades page
![hana-trades](https://user-images.githubusercontent.com/39964450/96374913-f7baea80-1175-11eb-80b9-cf33641cd8d4.png)
* Jobs page
![hana-jobs](https://user-images.githubusercontent.com/39964450/96374914-f984ae00-1175-11eb-9ea9-451d63649c4a.png)
