### ISSUE TITLE
feat(database): Database - models & scripts

### ISSUE THREAD

**Issue by Sciator** [Sciator/hana#7]
**Feature**
Create database with database scripts.

**Tasks**
- [ ] Setup database communication
- [ ] Example **typesafe** models
- [ ] Create database oneclick prepare scripts (TypeScript prefered so we can swap database and be still multiplatform)
- [ ] Add database configuration for dev/production (for production add way to create and manage configfile _- small dedicated app for config edit?_)
