### ISSUE TITLE
feat(common): Interface 

### ISSUE THREAD

**Issue by Sciator** [Sciator/hana#8]
**Feature**
Create common interface for ui-server and server-database.

**Task**
- [x] Review done analysis
- [x] Create ui-server-database interface types
- [ ] Create simple data mocks/examples
